services:
  sql:
    container_name: dhdv_sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "127.0.0.1:11433:1433"
    volumes:
      - ./backup:/var/opt/mssql/backup
      - sql_root:/var/opt/mssql
    networks:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd","-C","-S","localhost","-U","sa","-P","${MSSQL_SA_PASSWORD}","-Q","SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    container_name: dhdv_web
    build:
      context: ./src/DHDV.Web
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DHDV=${ConnectionStrings__DHDV}
      - HTTP_PORTS=
      - HTTPS_PORTS=
    depends_on:
      sql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      web:
        aliases: [web]
    volumes:
      - dp_keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8080/ready || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5


  cf:
    container_name: dhdv_cf
    image: cloudflare/cloudflared:2025.8.1
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run --token ${TUNNEL_TOKEN}
    depends_on:
      - web   # bá» condition: service_healthy
    networks:
      - web
    restart: unless-stopped

  smoker:
    image: curlimages/curl:8.10.1
    command: sh -c "while :; do d=$(date +%F_%T); curl -fsS http://web:8080/People >/dev/null && echo $$d OK || echo $$d FAIL; sleep 60; done | tee -a /logs/smoke_latest.log"
    volumes: [ "./logs:/logs" ]
    depends_on: [ web ]
    networks: [ web ]
    restart: unless-stopped


volumes:
  sql_root:
    external: true
    name: dhdv_stack_v_29_sql_root
  dp_keys:

networks:
  web:
    driver: bridge

